export const GENERATE_WALLET_SUCCESS = 'GENERATE_WALLET_SUCCESS'
export const GENERATE_KEYSTORE_SUCCESS = 'GENERATE_KEYSTORE_SUCCESS'


export const CHANGE_ACCOUNT_SUCCESS = 'CHANGE_ACCOUNT_SUCCESS'
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS'
export const INIT_TOKENS_SUCCESS = 'INIT_TOKENS_SUCCESS'

export const WALLET_CLOSE_SUCCESS = 'WALLET_CLOSE_SUCCESS'




export const LOAD_WALLET_REQUEST = 'LOAD_WALLET_REQUEST'
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET_SUCCESS'

export const GEN_SEED_REQUEST = 'GEN_SEED_REQUEST'
export const GEN_SEED_SUCCESS = 'GEN_SEED_SUCCESS'

export const RESTORE_FROM_SEED_REQUEST = 'RESTORE_FROM_SEED_REQUEST'
export const RESTORE_FROM_SEED_SUCCESS = 'RESTORE_FROM_SEED_SUCCESS'

export const RESTORE_FROM_KEYSTORE_REQUEST = 'RESTORE_FROM_KEYSTORE_REQUEST'
export const RESTORE_FROM_KEYSTORE_SUCCESS = 'RESTORE_FROM_KEYSTORE_SUCCESS'
export const RESTORE_FROM_KEYSTORE_ERROR = 'RESTORE_FROM_KEYSTORE_ERROR'

export const GEN_KEYSTORE_REQUEST = 'GEN_KEYSTORE_REQUEST'
export const GEN_KEYSTORE_SUCCESS = 'GEN_KEYSTORE_SUCCESS'

export const INIT_ACCOUNT_REQUEST = 'INIT_ACCOUNT_REQUEST'
export const INIT_ACCOUNT_SUCCESS = 'INIT_ACCOUNT_SUCCESS'

export const INIT_ACCOUNT_TOKENS_REQUEST = 'INIT_ACCOUNT_TOKENS_REQUEST'
export const INIT_ACCOUNT_TOKENS_SUCCESS = 'INIT_ACCOUNT_TOKENS_SUCCESS'

export const LOAD_NETWORK_REQUEST = 'LOAD_NETWORK_REQUEST'
export const LOAD_NETWORK_SUCCESS = 'LOAD_NETWORK_SUCCESS'
export const LOAD_NETWORK_ERROR = 'LOAD_NETWORK_ERROR'

export const ACCOUNT_CHANGE_REQUEST = 'ACCOUNT_CHANGE_REQUEST'
export const ACCOUNT_CHANGE_SUCCESS = 'ACCOUNT_CHANGE_SUCCESS'

export const NETWORK_CHANGE_REQUEST = 'NETWORK_CHANGE_REQUEST'
export const NETWORK_CHANGE_SUCCESS = 'NETWORK_CHANGE_SUCCESS'

export const GET_ALL_BALANCE_REQUEST = 'GET_ALL_BALANCE_REQUEST'
export const GET_ALL_BALANCE_SUCCESS = 'GET_ALL_BALANCE_SUCCESS'

export const WALLET_LOCK = 'WALLET_LOCK'

export const WALLET_UNLOCK = 'WALLET_UNLOCK'

export const WALLET_EXIT_SUCCESS = 'WALLET_EXIT_SUCCESS'

export const CREATE_NEW_ACCOUNT_REQUEST = 'CREATE_NEW_ACCOUNT_REQUEST'
export const CREATE_NEW_ACCOUNT_SUCCESS = 'CREATE_NEW_ACCOUNT_SUCCESS'

export const EDIT_ACCOUNT_REQUEST = 'EDIT_ACCOUNT_REQUEST'
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS'

export const DEL_ACCOUNT_REQUEST = 'DEL_ACCOUNT_REQUEST'
export const DEL_ACCOUNT_SUCCESS = 'DEL_ACCOUNT_SUCCESS'

export const ADD_TOKEN_REQUEST = 'ADD_TOKEN_REQUEST'
export const ADD_TOKEN_SUCCESS = 'ADD_TOKEN_SUCCESS'

export const DEL_TOKEN_REQUEST = 'DEL_TOKEN_REQUEST'
export const DEL_TOKEN_SUCCESS = 'DEL_TOKEN_SUCCESS'

export const GET_PRICE_REQUEST = 'GET_PRICE_REQUEST'
export const GET_PRICE_SUCCESS = 'GET_PRICE_SUCCESS'

export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS'

export const SYSTEM_ERROR = 'SYSTEM_ERROR'

export const CONTRACT_BUILD_REQUEST = 'CONTRACT_BUILD_REQUEST'
export const CONTRACT_BUILD_SUCCESS = 'CONTRACT_BUILD_SUCCESS'

export const ADD_CUSTOM_TOKEN_REQUEST = 'ADD_CUSTOM_TOKEN_REQUEST'
export const ADD_CUSTOM_TOKEN_SUCCESS = 'ADD_CUSTOM_TOKEN_SUCCESS'